
all:
	@echo "Run make with 'docs', 'tests' or 'psptests'. Check README for more info"

# Format autogenerated tests if clang-format is available (optional)
formatter=clang-format
ifeq (, $(shell which clang-format))
	formatter=true
endif

# Generates docs in HTML and PDF format (using weasyprint)
# Can alternative use wkhtmltopdf which is faster
.PHONY: docs
docs:
	mkdir -p docs/output/
	rm -f docs/output/index.html && ./gen-docs.py --format=html --output=docs/output/index.html
	rm -f docs/output/pdf_doc.html && ./gen-docs.py --format=pdf --output=docs/output/pdf_doc.html
	weasyprint docs/output/pdf_doc.html docs/output/docs.pdf && rm -f docs/output/pdf_doc.html

.PHONY: tests
tests:
	# Tests are dividied between files due to being too big!
	rm -f psp-tests/functional/autogen-test-*.c && \
		./gen-tests.py --output psp-tests/functional/autogen-test-%s.c --check-prefixes && \
		$(formatter) -i psp-tests/functional/autogen-test-*.c
	echo "AUTO_TEST_OBJS = \\" > psp-tests/functional/Makefile.auto
	(cd psp-tests/functional/ && echo "`ls autogen-test-*.c`" | sed "s/\\.c/.o \\\/g" >> Makefile.auto)
	rm -f psp-tests/performance/autogen-perftest.c && \
		./gen-perf-tests.py --output psp-tests/performance/autogen-perftest.c && \
		$(formatter) -i psp-tests/performance/autogen-perftest.c
	rm -f psp-tests/regcompat/autogen-regtests.c && \
		./gen-regtests.py --output psp-tests/regcompat/autogen-regtests.c && \
		$(formatter) -i psp-tests/regcompat/autogen-regtests.c

# Can build PBP or PRX:
# make psptests-clean && make psptests
# make psptests-clean BUILD_PRX=1 && make psptests BUILD_PRX=1

.PHONY: psptests
psptests:
	+make -C psp-tests/manual $(MAKEFLAGS) all
	+make -C psp-tests/functional $(MAKEFLAGS) all
	+make -C psp-tests/accuracy $(MAKEFLAGS) all
	+make -C psp-tests/performance $(MAKEFLAGS) all
	+make -C psp-tests/regcompat $(MAKEFLAGS) all
	+make -C psp-tests/manual/exception-module all

.PHONY: psptests-clean
psptests-clean:
	make -C psp-tests/manual clean
	make -C psp-tests/functional clean
	make -C psp-tests/accuracy clean
	make -C psp-tests/performance clean
	make -C psp-tests/regcompat clean
	make -C psp-tests/manual/exception-module clean

.PHONY: psptests-pbp-pack
psptests-pbp-pack:
	rm -f tests-release.zip
	zip -r tests-release.zip \
		psp-tests/manual/EBOOT.PBP \
		psp-tests/functional/EBOOT.PBP \
		psp-tests/accuracy/EBOOT.PBP \
		psp-tests/performance/EBOOT.PBP \
		psp-tests/regcompat/EBOOT.PBP \
		psp-tests/manual/exception-module/exception_module.prx

